// <auto-generated />
namespace BookReservationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Books : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Books));
        
        string IMigrationMetadata.Id
        {
            get { return "201706051838097_Books"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
